=== shoebking/XML-SCHEMA/Ekart.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="product">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="electronicdevices">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="name"/>
              <xs:element type="xs:string" name="price"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="clothes">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="mencloth">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="name"/>
                    <xs:element type="xs:string" name="price"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="kids">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="name"/>
                    <xs:element type="xs:string" name="price"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== shoebking/XML-SCHEMA/Ekart.xml
<?xml version="1.0"?>
<product xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Ekart.xsd">
    <electronicdevices>
        <name>Clock</name>
        <price>500</price>
    </electronicdevices>
    <clothes>
        <mencloth>
            <name>T-Shirts</name>
            <price>599</price>
        </mencloth>
        <kids>
            <name>Jeans</name>
            <price>999</price>
        </kids>
    </clothes>
</product>
